settings:
  PromptDuplicitFileCopy: true
  PromptDuplicitFileMove: true
  PromptDelete: true
  ShowHiddenFiles: true
  DefaultLinuxDriveMountLocation: /run/media/{UserName}/
  ShowMountedDrives: true
  